### ISSUE TITLE
Missed localization

### ISSUE THREAD

**Issue by geplus** [cromnix/pamac-classic#14]
Hi,
OS: Manjaro Linux
pamac-classic version: 6.6.2-1

The new version doesn't localize the language with the system (in my case the italian language, I don't konow if the other localizations have the same issue)

P.S: Regarding that, a nice feature to add in the future could be the language selection by the preferences' menu.

**Comment by cromerc** [comment]
That would be because Italian translation is incomplete:
https://github.com/cromnix/pamac-classic/blob/master/po/it.po

I don't speak Italian, so somebody will have to edit that file to create the translations to Italian.

My suggestion would be fork pamac-classic, then translate the english phrases to Italian in the fork, then open a pull request to merge the changes here.

**Comment by geplus** [comment]
Done :
#15 
I hope it will be merged, thank you

**Comment by cromerc** [comment]
I have merged your updates, let me know if it is working for you.
