### ISSUE TITLE
It seems that the preferences menu is not functional in the latest version...

### ISSUE THREAD

**Issue by hobbledehoy899** [cromnix/pamac-classic#9]
At first Pamac seems to freeze, but then a window saying "Waiting for another package manager to quit" pops up. The "terminal output" isn't helpful at all; there's no debug info to be seen when Pamac is ran from a terminal.

**Comment by cromerc** [comment]
I will take a look.

**Comment by cimarronline** [comment]
When I try to open the preferences in 6.3.3, nothing at all happens. Version 6.3.2 works fine.

**Comment by cromerc** [comment]
I believe I have found the problem, it is because of a translation problem with the dbus file, due to the translations failing the dbus file is blank. I am trying to figure out why the translations are failing.

Thanks for the words of support, I appreciate it. I have no idea if pamac-classic is in Manjaro's repos or not since I have never used Manjaro. I do know that it is in the AUR though which can be installed from Manjaro.

**Comment by cimarronline** [comment]
Thanks. Yes, it is in the Manjaro repos. Philip Müller, the main developer, put it there. I'm not the only fan...

**Comment by cromerc** [comment]
Found the root of the problem. The new itstool that came out 9 days ago fails to translate the polkit file. In the meantime I rolled back itstool on my notebook to 2.0.2 then recreated the polkit file. It should work now in 3.2.4, but I need to figure out why it fails with the new itstool so that this doesn't happen again in the future.

**Comment by cimarronline** [comment]
Yes, thank you. Version 6.3.4 works fine for me.

**Comment by cromerc** [comment]
I just found a way to fix the root of the problem and pushed 6.3.5. Now the package no longer depends on itstool to be built, it uses just gettext. This should prevent this problem from happening again in the future.

**Comment by cromerc** [comment]
Closed via: 6771e2cdf5f3c803b78f2eb2daf03015efc3ea47
